### ISSUE TITLE
configuration format documentation

### ISSUE THREAD

**Issue by Anze** [SylvanFranklin/srhd#7]
Hey there!
Your tool looks really interesting and promising. Could you please provide more detailed documentation about the configuration format it uses, especially for advanced use cases?

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a more detailed explanation of the configuration format, including advanced use cases and examples, to address the user's request for more comprehensive documentation.

You can review changes in this commit: https://github.com/lkilu6456546/SylvanFranklin-srhd-7/commit/8c220f6d22be132ab5b92fa2da8d3fd329e761ed.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by SylvanFranklin** [comment]
Yo! thanks for taking interest in the project! You make a great point about the key documentation, I was planning to make it more comprehensive for a while so I'll get that out asap! To answer briefly:
- I used a cross platform key listener internally in Rust, which uses the Unix terms for the keys. I originally wanted this project to be cross platform, but now I'm full macOS so that will be changed.
- I built this for myself initially and don't use those keys, but have no reason not to support them so will add.
- Same with `CapsLock`, `+`, and other symbols. All are trivial to implement, they just didn't fit my usecase, I'll release a new version that addresses this shortly.
